# Generated by Django 5.2.4 on 2025-12-12 22:58

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('hex_code', models.CharField(default='#000000', help_text='Hex color like #000000', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(help_text="Label shown to users (e.g. 'M', '39', 'XL').", max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional image used in category banners / thumbnails.', max_length=255, null=True, verbose_name='category_image')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=265, unique=True)),
                ('sku', models.CharField(help_text='Internal stock keeping unit.', max_length=64, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Shown near the price on the product page.', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Full description / long text.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price.', max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original / strike-through price (optional).', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g. USD, EUR, GBP).', max_length=3)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('allow_backorder', models.BooleanField(default=False, help_text='Allow ordering when stock is zero.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('image_main', cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image_main')),
                ('image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image_2')),
                ('image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image_3')),
                ('image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image_4')),
                ('image_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image_5')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured sections / home page.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='store.color')),
                ('sizes', models.ManyToManyField(blank=True, related_name='products', to='store.size')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='store.tag')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='store_produ_slug_361302_idx'), models.Index(fields=['status'], name='store_produ_status_3ab676_idx'), models.Index(fields=['category', 'status'], name='store_produ_categor_c5f89f_idx')],
            },
        ),
    ]
